#!/usr/bin/env bash

source profile

read -rd '' USAGE << 'EOF'
[CSR-RUNNER]

Executes systems and unit tests for critical system reconciliation.

Examples:
  # Execute all unit tests for the gcp system.
  csr-runner -e dev -s gcp -u all

  # Execute the cluster_name unit test for the gcp system.
  csr-runner -e dev -s gcp -u cluster_name

Flags:
  -e target environment
  -s target system 
  -u target unit test 

Usage:
  csr-runner [flags] [args]
EOF

if [[ $# -lt 6 ]]; then echo "${USAGE}"; fi
while getopts ":e:s:u:*" args
do
  case $args in
    e)  
      e=$2
      ;;
    s)
      s=$4
      ;;
    u)
      u=$6
      ;;
    *)
      echo "${USAGE}"
      ;;
  esac
done

if [[ -n ${e} ]] && \
   [[ -n ${s} ]] && \
   [[ -n ${u} ]]; then 
  echo -e "${M}#${N} Executing test in environment ${G}${e}${N} for system ${B}${s}${N} unit ${B}${u}${N} test:\n" ; "${PWD}"/"${e}"/"${s}"/unit/tests "${u}"
  exit
fi

shift $(($OPTIND -1))
